SELECT WANDS.ID,
       WANDS_PROPERTY.AGE,
       WANDS.COINS_NEEDED,
       WANDS.POWER
FROM WANDS
JOIN WANDS_PROPERTY ON WANDS.CODE = WANDS_PROPERTY.CODE
AND WANDS_PROPERTY.IS_EVIL = 0
WHERE (WANDS.power,
       WANDS.CODE,
       WANDS.COINS_NEEDED) IN
    (SELECT WANDS.POWER,
            WANDS.CODE,
            MIN(WANDS.COINS_NEEDED)
     FROM WANDS
     GROUP BY WANDS.POWER,
              WANDS.CODE)
ORDER BY WANDS.POWER DESC,
         WANDS_PROPERTY.AGE DESC;